<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Modelling</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">WQD7004</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="data_cleaning.html">Data Cleaning</a>
</li>
<li>
  <a href="data_summary.html">Codebook</a>
</li>
<li>
  <a href="data_exploration.html">Data Exploration</a>
</li>
<li>
  <a href="scatterplot.html">Scatterplot</a>
</li>
<li>
  <a href="data_modelling.html">Modelling</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Modelling</h1>

</div>


<div id="correlation" class="section level2">
<h2>Correlation</h2>
<ul>
<li>A correlation graph is used to identify attributes with high correlations.</li>
<li>This is useful in modelling as the model can use fewer attributes in the model to make an accurate prediction.</li>
</ul>
<pre class="r"><code>country_dataset &lt;- read.csv(&quot;data/imp_ses_efw.csv&quot;)
country_dataset &lt;- subset(country_dataset, select = -c(wbid,
                                                       unid,
                                                       country,
                                                       countries,
                                                       quartile,
                                                       rank,
                                                       popshare,
                                                       gdppc,
                                                       ECONOMIC_FREEDOM,
                                                       X1_size_government,
                                                       X2_property_rights,
                                                       X3_sound_money,
                                                       X4_trade,
                                                       X5_regulation
                                                       ))
country_correlation &lt;- cor(select_if(country_dataset, is.numeric), use=&quot;complete.obs&quot;, method=&quot;kendall&quot;) 

corrplot(country_correlation, method = &quot;circle&quot;, order = &quot;hclust&quot;, addrect = 3)</code></pre>
<p><img src="data_modelling_files/figure-html/correlation-1.png" width="1152" /></p>
</div>
<div id="train-machine-learning-models" class="section level2">
<h2>Train Machine Learning Models</h2>
<ul>
<li>Based on the results obtained from the correlation heatmap and scatterplot in the previous tab, the following attributes have been chosen to model our predictions:
<ul>
<li>year</li>
<li>X1a_government_consumption</li>
<li>X1b_transfers</li>
<li>X1c_gov_enterprises</li>
<li>X2c_protection_property_rights</li>
<li>X2e_integrity_legal_system</li>
<li>X2j_gender_adjustment</li>
<li>X3b_std_inflation</li>
<li>X3d_freedom_own_foreign_currency</li>
<li>X4a_tariffs</li>
<li>X4c_black_market</li>
<li>X4d_control_movement_capital_ppl</li>
<li>X5a_credit_market_reg</li>
</ul></li>
</ul>
<pre class="r"><code>complete_data = select(country_dataset,
        year,
        X1a_government_consumption,
        X1b_transfers,
        X1c_gov_enterprises,
        X2c_protection_property_rights,
        X2e_integrity_legal_system,
        X2j_gender_adjustment,
        X3b_std_inflation,
        X3d_freedom_own_foreign_currency,
        X4a_tariffs,
        X4c_black_market,
        X4d_control_movement_capital_ppl,
        X5a_credit_market_reg,
        SES
        )


#complete_data &lt;- na.omit(complete_data)
# Create model with default paramters
seed &lt;- 101
control &lt;- trainControl(method=&quot;repeatedcv&quot;, number=10, repeats=3)
metric &lt;- &quot;RMSE&quot;
preProcess=c(&quot;center&quot;, &quot;scale&quot;)

#Spilt train and test data
require(caTools)
set.seed(seed)
sample = sample.split(complete_data,SplitRatio = 0.80) 
train_data = subset(complete_data,sample == TRUE) 
test_data = subset(complete_data, sample == FALSE)

# Logistic Regression
set.seed(seed)
fit.glm &lt;- train(SES~., data=train_data, method=&quot;glm&quot;, trControl=control, na.action = na.omit)
# GLMNET
set.seed(seed)
fit.glmnet &lt;- train(SES~., data=train_data, method=&quot;glmnet&quot;, trControl=control, preProc=preProcess, na.action = na.omit)
# CART
set.seed(seed)
fit.cart &lt;- train(SES~., data=train_data, method=&quot;rpart&quot;, trControl=control, na.action = na.omit)
# Bagged CART
set.seed(seed)
fit.treebag &lt;- train(SES~., data=train_data, method=&quot;treebag&quot;, trControl=control, na.action = na.omit)
# Stochastic Gradient Boosting (Generalized Boosted Modeling)
set.seed(seed)
fit.gbm &lt;- train(SES~., data=train_data, method=&quot;gbm&quot;, trControl=control, na.action = na.omit, verbose=FALSE)

results &lt;- resamples(list(logistic=fit.glm, glmnet=fit.glmnet, cart=fit.cart, treebag=fit.treebag, gbm=fit.gbm))
# Table comparison
summary(results)</code></pre>
<pre><code>## 
## Call:
## summary.resamples(object = results)
## 
## Models: logistic, glmnet, cart, treebag, gbm 
## Number of resamples: 30 
## 
## MAE 
##               Min.  1st Qu.   Median     Mean  3rd Qu.     Max. NA&#39;s
## logistic 11.536055 13.65649 14.55944 14.62113 15.83965 17.70798    0
## glmnet   11.029522 13.75117 14.59927 14.56297 15.63441 17.36934    0
## cart     13.377918 16.76003 17.30709 17.53806 18.48855 22.41682    0
## treebag  10.330261 12.24696 12.88489 12.84224 13.28597 15.73408    0
## gbm       9.317087 11.10975 12.22744 11.80884 12.61553 13.55667    0
## 
## RMSE 
##              Min.  1st Qu.   Median     Mean  3rd Qu.     Max. NA&#39;s
## logistic 15.04774 17.63722 18.32404 18.48484 19.95143 21.53402    0
## glmnet   14.58781 17.38072 18.36862 18.47152 19.96603 21.26421    0
## cart     16.88728 21.15649 21.97414 22.14503 23.49707 27.51117    0
## treebag  12.80528 15.98988 16.74751 16.95158 17.61861 21.32256    0
## gbm      12.43275 14.80624 16.48129 16.18870 17.55256 19.29360    0
## 
## Rsquared 
##               Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA&#39;s
## logistic 0.4497941 0.5023568 0.5800932 0.5638451 0.6109143 0.7086714    0
## glmnet   0.4471034 0.4987881 0.5884886 0.5646136 0.6081706 0.7075611    0
## cart     0.1786834 0.2904327 0.3823592 0.3737742 0.4523569 0.5350654    0
## treebag  0.4558312 0.5983313 0.6364275 0.6331636 0.6887660 0.7360081    0
## gbm      0.5398935 0.6206200 0.6764403 0.6655150 0.6974503 0.7999423    0</code></pre>
<pre class="r"><code># boxplot comparison
bwplot(results)</code></pre>
<p><img src="data_modelling_files/figure-html/errplots-1.png" width="1152" /></p>
<pre class="r"><code># Dot-plot comparison
dotplot(results)</code></pre>
<p><img src="data_modelling_files/figure-html/errplots-2.png" width="1152" /></p>
</div>
<div id="predictions-from-test-data" class="section level2">
<h2>Predictions From Test Data</h2>
<pre class="r"><code>predictions &lt;- data.frame(test_data$SES)
predictions$logistic &lt;- predict(fit.glm, test_data)
predictions$glmnet &lt;- predict(fit.glmnet, test_data)
predictions$cart &lt;- predict(fit.cart, test_data)
predictions$treebag &lt;- predict(fit.treebag, test_data)
predictions$gbm &lt;- predict(fit.gbm, test_data)
kable(predictions)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">test_data.SES</th>
<th align="right">logistic</th>
<th align="right">glmnet</th>
<th align="right">cart</th>
<th align="right">treebag</th>
<th align="right">gbm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5.422691</td>
<td align="right">29.72735</td>
<td align="right">30.15097</td>
<td align="right">36.83542</td>
<td align="right">18.45133</td>
<td align="right">25.571634</td>
</tr>
<tr class="even">
<td align="right">52.497784</td>
<td align="right">78.54214</td>
<td align="right">75.05550</td>
<td align="right">36.83542</td>
<td align="right">63.50713</td>
<td align="right">71.098905</td>
</tr>
<tr class="odd">
<td align="right">79.976784</td>
<td align="right">54.71125</td>
<td align="right">52.25050</td>
<td align="right">61.74330</td>
<td align="right">54.78978</td>
<td align="right">59.314844</td>
</tr>
<tr class="even">
<td align="right">5.416281</td>
<td align="right">27.56004</td>
<td align="right">28.59315</td>
<td align="right">36.83542</td>
<td align="right">43.15048</td>
<td align="right">44.167916</td>
</tr>
<tr class="odd">
<td align="right">65.329811</td>
<td align="right">42.27178</td>
<td align="right">41.86197</td>
<td align="right">36.83542</td>
<td align="right">30.25468</td>
<td align="right">39.173995</td>
</tr>
<tr class="even">
<td align="right">65.900597</td>
<td align="right">74.04046</td>
<td align="right">71.46455</td>
<td align="right">61.74330</td>
<td align="right">60.91212</td>
<td align="right">71.985339</td>
</tr>
<tr class="odd">
<td align="right">83.364708</td>
<td align="right">89.57664</td>
<td align="right">86.78357</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">90.851632</td>
</tr>
<tr class="even">
<td align="right">80.834366</td>
<td align="right">85.24481</td>
<td align="right">83.18710</td>
<td align="right">75.24678</td>
<td align="right">81.25650</td>
<td align="right">84.754248</td>
</tr>
<tr class="odd">
<td align="right">53.789257</td>
<td align="right">56.11674</td>
<td align="right">55.73876</td>
<td align="right">36.83542</td>
<td align="right">47.45279</td>
<td align="right">47.987657</td>
</tr>
<tr class="even">
<td align="right">43.915085</td>
<td align="right">40.05551</td>
<td align="right">40.54988</td>
<td align="right">36.83542</td>
<td align="right">35.39861</td>
<td align="right">30.396224</td>
</tr>
<tr class="odd">
<td align="right">85.916916</td>
<td align="right">77.41666</td>
<td align="right">76.26265</td>
<td align="right">75.24678</td>
<td align="right">78.74461</td>
<td align="right">78.009624</td>
</tr>
<tr class="even">
<td align="right">48.906567</td>
<td align="right">59.10669</td>
<td align="right">56.90688</td>
<td align="right">61.74330</td>
<td align="right">49.01166</td>
<td align="right">61.291208</td>
</tr>
<tr class="odd">
<td align="right">77.943741</td>
<td align="right">81.24978</td>
<td align="right">79.04398</td>
<td align="right">75.24678</td>
<td align="right">76.50097</td>
<td align="right">77.884205</td>
</tr>
<tr class="even">
<td align="right">76.582840</td>
<td align="right">81.51052</td>
<td align="right">78.44165</td>
<td align="right">75.24678</td>
<td align="right">78.56161</td>
<td align="right">77.099143</td>
</tr>
<tr class="odd">
<td align="right">29.556179</td>
<td align="right">38.32500</td>
<td align="right">38.55507</td>
<td align="right">36.83542</td>
<td align="right">38.64982</td>
<td align="right">35.845001</td>
</tr>
<tr class="even">
<td align="right">27.381153</td>
<td align="right">48.23928</td>
<td align="right">47.26568</td>
<td align="right">36.83542</td>
<td align="right">29.58451</td>
<td align="right">27.336713</td>
</tr>
<tr class="odd">
<td align="right">90.860733</td>
<td align="right">94.85956</td>
<td align="right">91.44955</td>
<td align="right">75.24678</td>
<td align="right">81.25650</td>
<td align="right">89.284804</td>
</tr>
<tr class="even">
<td align="right">89.470291</td>
<td align="right">86.91626</td>
<td align="right">84.75377</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">87.489861</td>
</tr>
<tr class="odd">
<td align="right">73.292427</td>
<td align="right">67.35360</td>
<td align="right">65.42991</td>
<td align="right">75.24678</td>
<td align="right">79.99013</td>
<td align="right">74.524247</td>
</tr>
<tr class="even">
<td align="right">4.374566</td>
<td align="right">18.71226</td>
<td align="right">20.25886</td>
<td align="right">36.83542</td>
<td align="right">22.68351</td>
<td align="right">18.854238</td>
</tr>
<tr class="odd">
<td align="right">42.667175</td>
<td align="right">35.07534</td>
<td align="right">35.99938</td>
<td align="right">36.83542</td>
<td align="right">43.45293</td>
<td align="right">45.549127</td>
</tr>
<tr class="even">
<td align="right">43.619061</td>
<td align="right">44.67626</td>
<td align="right">44.42360</td>
<td align="right">36.83542</td>
<td align="right">41.54159</td>
<td align="right">28.151931</td>
</tr>
<tr class="odd">
<td align="right">15.382998</td>
<td align="right">53.96344</td>
<td align="right">53.53419</td>
<td align="right">36.83542</td>
<td align="right">36.58466</td>
<td align="right">39.481821</td>
</tr>
<tr class="even">
<td align="right">20.163912</td>
<td align="right">40.02174</td>
<td align="right">39.55853</td>
<td align="right">36.83542</td>
<td align="right">44.36264</td>
<td align="right">53.127403</td>
</tr>
<tr class="odd">
<td align="right">80.478775</td>
<td align="right">55.67110</td>
<td align="right">55.63586</td>
<td align="right">75.24678</td>
<td align="right">59.73411</td>
<td align="right">61.849845</td>
</tr>
<tr class="even">
<td align="right">93.042801</td>
<td align="right">83.22161</td>
<td align="right">80.99432</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">90.692301</td>
</tr>
<tr class="odd">
<td align="right">84.317146</td>
<td align="right">88.31915</td>
<td align="right">86.40433</td>
<td align="right">75.24678</td>
<td align="right">85.69964</td>
<td align="right">88.463102</td>
</tr>
<tr class="even">
<td align="right">4.153168</td>
<td align="right">29.75874</td>
<td align="right">32.74905</td>
<td align="right">36.83542</td>
<td align="right">27.11342</td>
<td align="right">17.404168</td>
</tr>
<tr class="odd">
<td align="right">96.900505</td>
<td align="right">89.17206</td>
<td align="right">87.65779</td>
<td align="right">75.24678</td>
<td align="right">80.11761</td>
<td align="right">82.730887</td>
</tr>
<tr class="even">
<td align="right">75.590805</td>
<td align="right">65.94467</td>
<td align="right">65.97242</td>
<td align="right">75.24678</td>
<td align="right">72.58479</td>
<td align="right">73.805733</td>
</tr>
<tr class="odd">
<td align="right">93.321754</td>
<td align="right">92.23792</td>
<td align="right">89.99494</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">89.498872</td>
</tr>
<tr class="even">
<td align="right">45.943970</td>
<td align="right">54.84823</td>
<td align="right">53.79337</td>
<td align="right">75.24678</td>
<td align="right">49.71243</td>
<td align="right">52.501398</td>
</tr>
<tr class="odd">
<td align="right">68.148262</td>
<td align="right">65.11672</td>
<td align="right">63.73445</td>
<td align="right">36.83542</td>
<td align="right">55.51094</td>
<td align="right">55.298417</td>
</tr>
<tr class="even">
<td align="right">46.549034</td>
<td align="right">44.25288</td>
<td align="right">43.66138</td>
<td align="right">61.74330</td>
<td align="right">45.19625</td>
<td align="right">44.514792</td>
</tr>
<tr class="odd">
<td align="right">81.889038</td>
<td align="right">89.12987</td>
<td align="right">86.98181</td>
<td align="right">61.74330</td>
<td align="right">73.40294</td>
<td align="right">72.772507</td>
</tr>
<tr class="even">
<td align="right">45.850662</td>
<td align="right">48.43276</td>
<td align="right">47.01569</td>
<td align="right">36.83542</td>
<td align="right">40.41498</td>
<td align="right">39.240259</td>
</tr>
<tr class="odd">
<td align="right">67.633354</td>
<td align="right">61.98286</td>
<td align="right">59.28585</td>
<td align="right">36.83542</td>
<td align="right">54.79799</td>
<td align="right">49.509747</td>
</tr>
<tr class="even">
<td align="right">89.554482</td>
<td align="right">79.17195</td>
<td align="right">77.90129</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">91.900728</td>
</tr>
<tr class="odd">
<td align="right">30.026346</td>
<td align="right">48.99400</td>
<td align="right">48.66010</td>
<td align="right">36.83542</td>
<td align="right">50.29606</td>
<td align="right">47.537973</td>
</tr>
<tr class="even">
<td align="right">80.763268</td>
<td align="right">63.18372</td>
<td align="right">62.19001</td>
<td align="right">75.24678</td>
<td align="right">75.07090</td>
<td align="right">80.014725</td>
</tr>
<tr class="odd">
<td align="right">69.058830</td>
<td align="right">54.39499</td>
<td align="right">54.06992</td>
<td align="right">75.24678</td>
<td align="right">71.23755</td>
<td align="right">60.871780</td>
</tr>
<tr class="even">
<td align="right">7.062064</td>
<td align="right">51.70662</td>
<td align="right">50.02177</td>
<td align="right">36.83542</td>
<td align="right">44.05360</td>
<td align="right">44.912053</td>
</tr>
<tr class="odd">
<td align="right">71.970253</td>
<td align="right">78.20399</td>
<td align="right">75.25082</td>
<td align="right">61.74330</td>
<td align="right">52.59619</td>
<td align="right">61.144893</td>
</tr>
<tr class="even">
<td align="right">67.865219</td>
<td align="right">39.36732</td>
<td align="right">40.09505</td>
<td align="right">36.83542</td>
<td align="right">37.72532</td>
<td align="right">43.994726</td>
</tr>
<tr class="odd">
<td align="right">35.242714</td>
<td align="right">65.23871</td>
<td align="right">64.44485</td>
<td align="right">36.83542</td>
<td align="right">53.64143</td>
<td align="right">51.493136</td>
</tr>
<tr class="even">
<td align="right">87.235619</td>
<td align="right">85.51418</td>
<td align="right">83.82192</td>
<td align="right">75.24678</td>
<td align="right">79.47470</td>
<td align="right">78.021021</td>
</tr>
<tr class="odd">
<td align="right">93.119057</td>
<td align="right">91.64393</td>
<td align="right">89.02336</td>
<td align="right">75.24678</td>
<td align="right">83.95695</td>
<td align="right">88.146728</td>
</tr>
<tr class="even">
<td align="right">55.720093</td>
<td align="right">45.48757</td>
<td align="right">44.51398</td>
<td align="right">75.24678</td>
<td align="right">50.80710</td>
<td align="right">58.388147</td>
</tr>
<tr class="odd">
<td align="right">76.126053</td>
<td align="right">74.75526</td>
<td align="right">73.58371</td>
<td align="right">61.74330</td>
<td align="right">65.39525</td>
<td align="right">69.540690</td>
</tr>
<tr class="even">
<td align="right">24.035835</td>
<td align="right">74.12434</td>
<td align="right">71.71796</td>
<td align="right">75.24678</td>
<td align="right">82.16265</td>
<td align="right">76.440500</td>
</tr>
<tr class="odd">
<td align="right">45.643185</td>
<td align="right">49.34832</td>
<td align="right">48.35364</td>
<td align="right">75.24678</td>
<td align="right">55.13757</td>
<td align="right">70.532572</td>
</tr>
<tr class="even">
<td align="right">8.692344</td>
<td align="right">17.63172</td>
<td align="right">19.14087</td>
<td align="right">36.83542</td>
<td align="right">16.03110</td>
<td align="right">20.935608</td>
</tr>
<tr class="odd">
<td align="right">83.078407</td>
<td align="right">75.18451</td>
<td align="right">73.18494</td>
<td align="right">36.83542</td>
<td align="right">63.80776</td>
<td align="right">61.056572</td>
</tr>
<tr class="even">
<td align="right">72.783783</td>
<td align="right">41.35809</td>
<td align="right">40.89208</td>
<td align="right">61.74330</td>
<td align="right">46.42926</td>
<td align="right">61.202359</td>
</tr>
<tr class="odd">
<td align="right">7.198971</td>
<td align="right">20.11651</td>
<td align="right">23.45006</td>
<td align="right">36.83542</td>
<td align="right">32.98473</td>
<td align="right">38.668625</td>
</tr>
<tr class="even">
<td align="right">67.829681</td>
<td align="right">43.36599</td>
<td align="right">43.34344</td>
<td align="right">36.83542</td>
<td align="right">58.21266</td>
<td align="right">61.399657</td>
</tr>
<tr class="odd">
<td align="right">70.576118</td>
<td align="right">70.84824</td>
<td align="right">69.65890</td>
<td align="right">61.74330</td>
<td align="right">59.47852</td>
<td align="right">71.035160</td>
</tr>
<tr class="even">
<td align="right">83.746834</td>
<td align="right">92.53392</td>
<td align="right">89.99993</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">92.966838</td>
</tr>
<tr class="odd">
<td align="right">81.940880</td>
<td align="right">94.42747</td>
<td align="right">91.92582</td>
<td align="right">75.24678</td>
<td align="right">83.64084</td>
<td align="right">91.280581</td>
</tr>
<tr class="even">
<td align="right">62.215469</td>
<td align="right">52.32842</td>
<td align="right">52.89880</td>
<td align="right">36.83542</td>
<td align="right">48.14531</td>
<td align="right">64.312063</td>
</tr>
<tr class="odd">
<td align="right">46.568325</td>
<td align="right">46.68361</td>
<td align="right">46.90846</td>
<td align="right">36.83542</td>
<td align="right">50.43243</td>
<td align="right">53.339170</td>
</tr>
<tr class="even">
<td align="right">89.359589</td>
<td align="right">82.07822</td>
<td align="right">81.30084</td>
<td align="right">75.24678</td>
<td align="right">83.64084</td>
<td align="right">88.773615</td>
</tr>
<tr class="odd">
<td align="right">55.010235</td>
<td align="right">42.06327</td>
<td align="right">41.16490</td>
<td align="right">36.83542</td>
<td align="right">48.10546</td>
<td align="right">54.700603</td>
</tr>
<tr class="even">
<td align="right">75.507393</td>
<td align="right">71.28977</td>
<td align="right">70.28663</td>
<td align="right">75.24678</td>
<td align="right">76.50097</td>
<td align="right">77.258025</td>
</tr>
<tr class="odd">
<td align="right">73.511864</td>
<td align="right">66.83642</td>
<td align="right">65.27731</td>
<td align="right">75.24678</td>
<td align="right">78.56161</td>
<td align="right">79.681179</td>
</tr>
<tr class="even">
<td align="right">31.556787</td>
<td align="right">39.29873</td>
<td align="right">40.54247</td>
<td align="right">36.83542</td>
<td align="right">52.16995</td>
<td align="right">53.737564</td>
</tr>
<tr class="odd">
<td align="right">27.963875</td>
<td align="right">33.70061</td>
<td align="right">35.13151</td>
<td align="right">36.83542</td>
<td align="right">34.36721</td>
<td align="right">34.834639</td>
</tr>
<tr class="even">
<td align="right">93.744499</td>
<td align="right">102.34779</td>
<td align="right">99.99253</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">92.233202</td>
</tr>
<tr class="odd">
<td align="right">97.044762</td>
<td align="right">103.67379</td>
<td align="right">101.01107</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">90.741551</td>
</tr>
<tr class="even">
<td align="right">80.802002</td>
<td align="right">76.69040</td>
<td align="right">75.29862</td>
<td align="right">75.24678</td>
<td align="right">82.65211</td>
<td align="right">83.263013</td>
</tr>
<tr class="odd">
<td align="right">3.030765</td>
<td align="right">28.28946</td>
<td align="right">29.65553</td>
<td align="right">36.83542</td>
<td align="right">19.28298</td>
<td align="right">23.523222</td>
</tr>
<tr class="even">
<td align="right">39.190258</td>
<td align="right">32.74095</td>
<td align="right">34.58033</td>
<td align="right">36.83542</td>
<td align="right">32.82601</td>
<td align="right">29.259305</td>
</tr>
<tr class="odd">
<td align="right">49.430176</td>
<td align="right">41.64920</td>
<td align="right">42.68368</td>
<td align="right">75.24678</td>
<td align="right">56.90483</td>
<td align="right">53.833648</td>
</tr>
<tr class="even">
<td align="right">19.053106</td>
<td align="right">42.90815</td>
<td align="right">43.32450</td>
<td align="right">36.83542</td>
<td align="right">46.03719</td>
<td align="right">37.409576</td>
</tr>
<tr class="odd">
<td align="right">16.132523</td>
<td align="right">21.51396</td>
<td align="right">23.96300</td>
<td align="right">36.83542</td>
<td align="right">16.36472</td>
<td align="right">19.919770</td>
</tr>
<tr class="even">
<td align="right">80.109383</td>
<td align="right">67.91525</td>
<td align="right">68.21870</td>
<td align="right">75.24678</td>
<td align="right">67.84642</td>
<td align="right">75.572975</td>
</tr>
<tr class="odd">
<td align="right">92.742691</td>
<td align="right">86.87325</td>
<td align="right">85.49663</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">90.171422</td>
</tr>
<tr class="even">
<td align="right">87.364433</td>
<td align="right">100.19490</td>
<td align="right">98.20901</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">91.429197</td>
</tr>
<tr class="odd">
<td align="right">3.629181</td>
<td align="right">30.08708</td>
<td align="right">32.85571</td>
<td align="right">36.83542</td>
<td align="right">16.06730</td>
<td align="right">6.736908</td>
</tr>
<tr class="even">
<td align="right">91.345139</td>
<td align="right">90.89707</td>
<td align="right">89.72625</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">92.019684</td>
</tr>
<tr class="odd">
<td align="right">81.399338</td>
<td align="right">66.91785</td>
<td align="right">66.99998</td>
<td align="right">75.24678</td>
<td align="right">75.89558</td>
<td align="right">79.239821</td>
</tr>
<tr class="even">
<td align="right">89.487686</td>
<td align="right">106.00505</td>
<td align="right">103.36681</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">91.644729</td>
</tr>
<tr class="odd">
<td align="right">59.640270</td>
<td align="right">42.47434</td>
<td align="right">44.25448</td>
<td align="right">75.24678</td>
<td align="right">50.85692</td>
<td align="right">43.178049</td>
</tr>
<tr class="even">
<td align="right">68.662956</td>
<td align="right">56.74335</td>
<td align="right">57.87767</td>
<td align="right">61.74330</td>
<td align="right">33.13416</td>
<td align="right">40.580110</td>
</tr>
<tr class="odd">
<td align="right">37.950760</td>
<td align="right">49.25114</td>
<td align="right">50.26112</td>
<td align="right">61.74330</td>
<td align="right">52.38928</td>
<td align="right">52.737436</td>
</tr>
<tr class="even">
<td align="right">85.260384</td>
<td align="right">76.60032</td>
<td align="right">75.99748</td>
<td align="right">61.74330</td>
<td align="right">69.47642</td>
<td align="right">84.355122</td>
</tr>
<tr class="odd">
<td align="right">38.218887</td>
<td align="right">56.20815</td>
<td align="right">56.19800</td>
<td align="right">61.74330</td>
<td align="right">50.57241</td>
<td align="right">53.606785</td>
</tr>
<tr class="even">
<td align="right">73.885284</td>
<td align="right">66.51774</td>
<td align="right">65.73706</td>
<td align="right">61.74330</td>
<td align="right">47.11809</td>
<td align="right">35.605861</td>
</tr>
<tr class="odd">
<td align="right">88.742493</td>
<td align="right">83.95700</td>
<td align="right">82.90360</td>
<td align="right">75.24678</td>
<td align="right">85.30332</td>
<td align="right">89.432340</td>
</tr>
<tr class="even">
<td align="right">28.615171</td>
<td align="right">54.12728</td>
<td align="right">54.24689</td>
<td align="right">61.74330</td>
<td align="right">50.41487</td>
<td align="right">52.797009</td>
</tr>
<tr class="odd">
<td align="right">83.030815</td>
<td align="right">60.50524</td>
<td align="right">61.62609</td>
<td align="right">75.24678</td>
<td align="right">78.56161</td>
<td align="right">66.970120</td>
</tr>
<tr class="even">
<td align="right">59.405224</td>
<td align="right">58.49933</td>
<td align="right">58.98475</td>
<td align="right">75.24678</td>
<td align="right">71.86283</td>
<td align="right">63.530221</td>
</tr>
<tr class="odd">
<td align="right">4.251631</td>
<td align="right">32.89761</td>
<td align="right">36.36337</td>
<td align="right">36.83542</td>
<td align="right">44.71180</td>
<td align="right">46.912816</td>
</tr>
<tr class="even">
<td align="right">74.420036</td>
<td align="right">72.97568</td>
<td align="right">71.97439</td>
<td align="right">75.24678</td>
<td align="right">68.70225</td>
<td align="right">68.599608</td>
</tr>
<tr class="odd">
<td align="right">66.870972</td>
<td align="right">54.06236</td>
<td align="right">53.93054</td>
<td align="right">36.83542</td>
<td align="right">49.54752</td>
<td align="right">47.098840</td>
</tr>
<tr class="even">
<td align="right">7.146506</td>
<td align="right">54.06813</td>
<td align="right">54.45372</td>
<td align="right">36.83542</td>
<td align="right">43.78680</td>
<td align="right">40.902663</td>
</tr>
<tr class="odd">
<td align="right">85.628975</td>
<td align="right">81.52952</td>
<td align="right">80.74566</td>
<td align="right">75.24678</td>
<td align="right">76.67304</td>
<td align="right">80.621207</td>
</tr>
<tr class="even">
<td align="right">92.655121</td>
<td align="right">100.84125</td>
<td align="right">98.40618</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">91.644729</td>
</tr>
<tr class="odd">
<td align="right">48.872055</td>
<td align="right">32.40953</td>
<td align="right">35.91862</td>
<td align="right">36.83542</td>
<td align="right">41.50565</td>
<td align="right">36.921952</td>
</tr>
<tr class="even">
<td align="right">59.662266</td>
<td align="right">62.42840</td>
<td align="right">63.20565</td>
<td align="right">75.24678</td>
<td align="right">76.02466</td>
<td align="right">72.967815</td>
</tr>
<tr class="odd">
<td align="right">26.488094</td>
<td align="right">50.11481</td>
<td align="right">51.57391</td>
<td align="right">61.74330</td>
<td align="right">44.03083</td>
<td align="right">41.109577</td>
</tr>
<tr class="even">
<td align="right">38.874393</td>
<td align="right">60.52237</td>
<td align="right">59.24396</td>
<td align="right">75.24678</td>
<td align="right">73.87620</td>
<td align="right">61.858842</td>
</tr>
<tr class="odd">
<td align="right">2.225223</td>
<td align="right">44.64206</td>
<td align="right">46.36281</td>
<td align="right">36.83542</td>
<td align="right">31.12130</td>
<td align="right">21.921400</td>
</tr>
<tr class="even">
<td align="right">78.304153</td>
<td align="right">69.51530</td>
<td align="right">69.12979</td>
<td align="right">75.24678</td>
<td align="right">73.93386</td>
<td align="right">70.110573</td>
</tr>
<tr class="odd">
<td align="right">86.096413</td>
<td align="right">59.40457</td>
<td align="right">60.61827</td>
<td align="right">61.74330</td>
<td align="right">71.93769</td>
<td align="right">76.746574</td>
</tr>
<tr class="even">
<td align="right">9.909722</td>
<td align="right">35.28151</td>
<td align="right">37.93686</td>
<td align="right">36.83542</td>
<td align="right">30.59957</td>
<td align="right">30.033658</td>
</tr>
<tr class="odd">
<td align="right">2.164493</td>
<td align="right">37.37556</td>
<td align="right">39.11950</td>
<td align="right">36.83542</td>
<td align="right">34.46800</td>
<td align="right">20.536645</td>
</tr>
<tr class="even">
<td align="right">37.508343</td>
<td align="right">29.84466</td>
<td align="right">33.22802</td>
<td align="right">36.83542</td>
<td align="right">38.50870</td>
<td align="right">26.361971</td>
</tr>
<tr class="odd">
<td align="right">85.359718</td>
<td align="right">74.63264</td>
<td align="right">74.40266</td>
<td align="right">75.24678</td>
<td align="right">85.30332</td>
<td align="right">89.986018</td>
</tr>
<tr class="even">
<td align="right">2.212363</td>
<td align="right">33.28443</td>
<td align="right">37.41896</td>
<td align="right">75.24678</td>
<td align="right">64.86575</td>
<td align="right">47.692987</td>
</tr>
<tr class="odd">
<td align="right">87.093582</td>
<td align="right">92.31297</td>
<td align="right">91.09759</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">92.179726</td>
</tr>
<tr class="even">
<td align="right">31.078709</td>
<td align="right">57.93856</td>
<td align="right">57.82975</td>
<td align="right">61.74330</td>
<td align="right">42.31342</td>
<td align="right">41.374696</td>
</tr>
<tr class="odd">
<td align="right">16.868803</td>
<td align="right">36.92923</td>
<td align="right">38.79434</td>
<td align="right">36.83542</td>
<td align="right">26.46216</td>
<td align="right">14.742587</td>
</tr>
<tr class="even">
<td align="right">87.218033</td>
<td align="right">80.96508</td>
<td align="right">80.01565</td>
<td align="right">75.24678</td>
<td align="right">81.34216</td>
<td align="right">84.196630</td>
</tr>
<tr class="odd">
<td align="right">82.860207</td>
<td align="right">54.60240</td>
<td align="right">55.60104</td>
<td align="right">36.83542</td>
<td align="right">43.90797</td>
<td align="right">46.671670</td>
</tr>
<tr class="even">
<td align="right">42.923637</td>
<td align="right">53.64314</td>
<td align="right">53.68463</td>
<td align="right">36.83542</td>
<td align="right">52.93603</td>
<td align="right">58.753207</td>
</tr>
<tr class="odd">
<td align="right">23.123371</td>
<td align="right">44.79632</td>
<td align="right">45.57660</td>
<td align="right">36.83542</td>
<td align="right">47.19195</td>
<td align="right">43.753746</td>
</tr>
<tr class="even">
<td align="right">76.681602</td>
<td align="right">53.45192</td>
<td align="right">54.48215</td>
<td align="right">75.24678</td>
<td align="right">78.07865</td>
<td align="right">64.326369</td>
</tr>
<tr class="odd">
<td align="right">84.051285</td>
<td align="right">79.48636</td>
<td align="right">78.94079</td>
<td align="right">75.24678</td>
<td align="right">85.30332</td>
<td align="right">89.459962</td>
</tr>
<tr class="even">
<td align="right">11.088360</td>
<td align="right">49.06998</td>
<td align="right">50.44031</td>
<td align="right">75.24678</td>
<td align="right">53.11199</td>
<td align="right">42.214806</td>
</tr>
<tr class="odd">
<td align="right">90.625130</td>
<td align="right">98.41113</td>
<td align="right">96.83504</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">90.807536</td>
</tr>
<tr class="even">
<td align="right">5.808696</td>
<td align="right">31.82258</td>
<td align="right">34.32342</td>
<td align="right">36.83542</td>
<td align="right">26.41520</td>
<td align="right">30.726147</td>
</tr>
<tr class="odd">
<td align="right">90.699150</td>
<td align="right">85.85778</td>
<td align="right">84.97723</td>
<td align="right">75.24678</td>
<td align="right">86.21641</td>
<td align="right">89.632644</td>
</tr>
<tr class="even">
<td align="right">86.174202</td>
<td align="right">56.26304</td>
<td align="right">57.39868</td>
<td align="right">75.24678</td>
<td align="right">68.90112</td>
<td align="right">63.478048</td>
</tr>
<tr class="odd">
<td align="right">83.356682</td>
<td align="right">78.59403</td>
<td align="right">78.82399</td>
<td align="right">75.24678</td>
<td align="right">77.20911</td>
<td align="right">68.815889</td>
</tr>
<tr class="even">
<td align="right">18.333456</td>
<td align="right">34.62505</td>
<td align="right">37.37788</td>
<td align="right">36.83542</td>
<td align="right">30.36431</td>
<td align="right">19.906161</td>
</tr>
<tr class="odd">
<td align="right">59.099377</td>
<td align="right">41.71439</td>
<td align="right">43.44817</td>
<td align="right">36.83542</td>
<td align="right">39.44816</td>
<td align="right">30.731255</td>
</tr>
<tr class="even">
<td align="right">83.329819</td>
<td align="right">56.40992</td>
<td align="right">56.95836</td>
<td align="right">75.24678</td>
<td align="right">71.53813</td>
<td align="right">58.309432</td>
</tr>
<tr class="odd">
<td align="right">56.942608</td>
<td align="right">48.07931</td>
<td align="right">50.26225</td>
<td align="right">75.24678</td>
<td align="right">78.87318</td>
<td align="right">77.305456</td>
</tr>
<tr class="even">
<td align="right">27.127140</td>
<td align="right">52.41975</td>
<td align="right">53.65459</td>
<td align="right">61.74330</td>
<td align="right">49.40658</td>
<td align="right">55.565939</td>
</tr>
</tbody>
</table>
</div>
<div id="scoring-the-predictions" class="section level2">
<h2>Scoring the predictions</h2>
<ul>
<li>For our score, we expect:
<ul>
<li>A Root Mean Square Error (RMSE) of &lt; 20</li>
<li>A Root Relative Squared Error (RRSE) of &lt; 0.6</li>
</ul></li>
<li>If the model meets the above criteria, it will be considered a success.</li>
</ul>
<pre class="r"><code>    model_list &lt;- &quot;Logistic Regression&quot;
    rmse_score &lt;- as.character(
      rmse(predictions$test_data.SES,predictions$logistic)
    )
    rrse_score &lt;- as.character(
      rrse(predictions$test_data.SES,predictions$logistic)
    )
    
    model_list &lt;- append(model_list, &quot;GLMNET&quot;)
    rmse_score &lt;-  append(
      rmse_score, 
      rmse(predictions$test_data.SES,predictions$glmnet)
    )
    rrse_score &lt;-  append(
      rrse_score, 
      rrse(predictions$test_data.SES,predictions$glmnet)
    )

    model_list &lt;- append(model_list, &quot;CART&quot;)
    rmse_score &lt;-  append(
      rmse_score, 
      rmse(predictions$test_data.SES,predictions$cart)
    )
    rrse_score &lt;-  append(
      rrse_score, 
      rrse(predictions$test_data.SES,predictions$cart)
    )

    model_list &lt;- append(model_list, &quot;Treebag&quot;)
    rmse_score &lt;-  append(
      rmse_score, 
      rmse(predictions$test_data.SES,predictions$treebag)
    )
    rrse_score &lt;-  append(
      rrse_score, 
      rrse(predictions$test_data.SES,predictions$treebag)
    )

    model_list &lt;- append(model_list, &quot;GBM&quot;)
    rmse_score &lt;-  append(
      rmse_score, 
      rmse(predictions$test_data.SES,predictions$gbm)
    )
    rrse_score &lt;-  append(
      rrse_score, 
      rrse(predictions$test_data.SES,predictions$gbm)
    )

    prediction &lt;- data.frame(model_list, rmse_score, rrse_score)
    prediction1 &lt;- data.frame(model_list, rmse_score)
    prediction2 &lt;- data.frame(model_list, rrse_score)
    
    colnames(prediction)[1] &lt;- &quot;Model&quot;
    colnames(prediction)[2] &lt;- &quot;RMSE&quot;
    colnames(prediction)[3] &lt;- &quot;RRSE&quot;
    
    colnames(prediction1)[1] &lt;- &quot;Model&quot;
    colnames(prediction1)[2] &lt;- &quot;RMSE&quot;
    colnames(prediction2)[1] &lt;- &quot;Model&quot;
    colnames(prediction2)[2] &lt;- &quot;RRSE&quot;
    kable(prediction)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Model</th>
<th align="left">RMSE</th>
<th align="left">RRSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Logistic Regression</td>
<td align="left">17.8355430107563</td>
<td align="left">0.602024619097772</td>
</tr>
<tr class="even">
<td align="left">GLMNET</td>
<td align="left">18.0271043052409</td>
<td align="left">0.608490618774734</td>
</tr>
<tr class="odd">
<td align="left">CART</td>
<td align="left">21.9158804441193</td>
<td align="left">0.739753175364846</td>
</tr>
<tr class="even">
<td align="left">Treebag</td>
<td align="left">17.6720721660914</td>
<td align="left">0.596506790291909</td>
</tr>
<tr class="odd">
<td align="left">GBM</td>
<td align="left">16.75691996891</td>
<td align="left">0.565616553163026</td>
</tr>
</tbody>
</table>
<pre class="r"><code>prediction1$rmse &lt;- as.numeric(as.character(prediction1$RMSE))
prediction1 &lt;- subset(prediction1, select = -c(RMSE))
prediction_m1 &lt;- gather(prediction1, variable, value, -Model, convert = FALSE)
ggplot(data = prediction_m1, aes(x = variable, y = value, fill = Model)) +
  geom_col(position = position_dodge()) + ylab(&quot;RMSE&quot;) + xlab(&quot;Model&quot;)</code></pre>
<p><img src="data_modelling_files/figure-html/unnamed-chunk-4-1.png" width="1152" /></p>
<pre class="r"><code>prediction2$rrse &lt;- as.numeric(as.character(prediction2$RRSE))
prediction2 &lt;- subset(prediction2, select = -c(RRSE))
prediction_m2 &lt;- gather(prediction2, variable, value, -Model, convert = FALSE)
ggplot(data = prediction_m2, aes(x = variable, y = value, fill = Model)) +
  geom_col(position = position_dodge()) + ylab(&quot;RRSE&quot;) + xlab(&quot;Model&quot;)</code></pre>
<p><img src="data_modelling_files/figure-html/unnamed-chunk-5-1.png" width="1152" /></p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions:</h2>
<p>From our findings, GBM produces the best results among the tested models with the lowest mean absolute percentage error (RMSE) of 16.75, and Root Relative Squared Error (RRSE) of 0.5656.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
